wbatchsize = 2048
filename_prefix = "processed."
test_batch_size = 64
eval_steps = 2000
max_train_epoch = 20
max_training_steps = 100000
max_decode_len = 256
input_dir = 'temp/run_en_vi_spm/data'
vocab_file = input_dir + '/processed.vocab.pickle'
